name: lagrangian-csf-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - ipython
  - fenics-dolfinx
  - adios4dolfinx
  - scifem
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pyvista
  - git
  - mpich
  - colormaps
  - imageio
  - gmsh
  - pip:
     - gmsh
